# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a4a7ac8fc1d36ebebc6aa6366a5354c9b836d5c535d0c215dce4fc283ec9684b733da8edae7c4dcbc5af1c5f5ceeb3dee1c8c5ed4561d367317a6d6110ccb5e

test:
  secret_key_base: 61c1a09d883675adb7daef35c72c6e475e2de8c7d1d6627f974c973948bdd4a8bbddc867ef0b19416e6b271989a35ab59b123b2190f1e34b5f0b2c3623e2ce98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
